from typing import TypedDict, Literal, Any
from dataclasses import dataclass

class PasswordProfileJson(TypedDict):
    forceChangePasswordNextSignIn: bool
    password: str

type UserType = Literal["member", "guest"]

class CreateUserJson(TypedDict):
    # The status of the account. Can be true or false.
    accountEnabled: bool

    # The name in displayed in the directory. This is the full name of the user.
    displayName: str

    # The mail alias of the user. This should be `user` of `user@domain.com`, as it is by default.
    mailNickname: str

    # The "email" of the user, or the principal name. For example, `user@domain.com`.
    userPrincipalName: str

    # The type of user, this is either Member or Guest. This will be a setting to enable
    # in the options. It will apply to every user being created.
    userType: UserType

    # The password profile of the user.
    passwordProfile: PasswordProfileJson

    # The first name of the user.
    givenName: str

    # The last name of the user.
    surname: str

@dataclass
class RequestErrorResponse:
    '''A class representing the error response of a Graph request.'''
    code: str = ""
    message: str = ""
    date: str = ""
    request_id: str = ""
    # The property field of the Graph User that failed.
    target: str = ""

    def format_error(self) -> str:
        '''Returns a client-safe error code formatted into a string from the error data.'''
        l_code: str = self.code.lower()
        l_target: str = self.target.lower() if self.target != "" else "unknownTarget"

        error_map: dict[tuple[str, str], str] = {
            ("invalidvalue", "userprincipalname"): "Invalid UPN domain",
            ("objectconflict", "userprincipalname"): "UPN already exists",
        }

        tup_key = (l_code, l_target)
        default_error: str = f"An unknown error occurred ({self.target}, see application logs for details)"

        err: str | None = error_map.get(tup_key, None)
        if err is None:
            err = default_error
        else:
            err = f"{err} ({self.target})"
        
        return err

JsonHeaders = TypedDict("JsonHeaders",
    {
        "authorization": str,
        "content-type": str,
    }
)

class GraphAccountCacheReader(TypedDict):
    # A list of dictionary objects which are the accounts. The dictionary of
    # the list is used to authenticate silently.
    #
    # The dictionary schema is generated by MSAL, and the only key that will
    # be used is the `username` key.
    #
    # If for whatever reason the `username` key does not exist, then it will use
    # the last value in the cache as a fallback.
    account_cache: list[dict[str, Any]]

    # The most recent account login. This is the username/principal name,
    # for example: `user@domain.com`. This is used to get the most recent
    # user if multiple users exist in the cache.
    recent_username: str

class FailedUserObject(TypedDict):
    '''Used in GraphError to represent a failed user.'''
    name: str
    # The error message. This will be displayed after the name,
    # for example: John Doe: An error (target).
    error: str

class GraphError(TypedDict):
    '''Represents an error object from Graph. This is used in the front end and
    *should not be logged* due to the usernames.
    '''
    # The time of the failure in seconds.
    timestamp: float
    total_users_count: int
    failed_users_count: int
    # Users that failed to get created.
    failed_users: list[FailedUserObject]