from typing import TypedDict, Literal, Any
from dataclasses import dataclass

class PasswordProfileJson(TypedDict):
    forceChangePasswordNextSignIn: bool
    password: str

type UserType = Literal["member", "guest"]

class CreateUserJson(TypedDict):
    # The status of the account. Can be true or false.
    accountEnabled: bool

    # The name in displayed in the directory. This is the full name of the user.
    displayName: str

    # The mail alias of the user. This should be `user` of `user@domain.com`, as it is by default.
    mailNickname: str

    # The "email" of the user, or the principal name. For example, `user@domain.com`.
    userPrincipalName: str

    # The type of user, this is either Member or Guest. This will be a setting to enable
    # in the options. It will apply to every user being created.
    userType: UserType

    # The password profile of the user.
    passwordProfile: PasswordProfileJson

    # The first name of the user.
    givenName: str

    # The last name of the user.
    surname: str

@dataclass
class RequestErrorResponse:
    '''A class representing the error response of a Graph request.'''
    code: str = ""
    message: str = ""
    date: str = ""
    request_id: str = ""
    target: str = ""

JsonHeaders = TypedDict("JsonHeaders",
    {
        "authorization": str,
        "content-type": str,
    }
)

class GraphAccountCacheReader(TypedDict):
    # A list of dictionary objects which are the accounts. The dictionary of
    # the list is used to authenticate silently.
    #
    # The dictionary schema is generated by MSAL, and the only key that will
    # be used is the `username` key.
    #
    # If for whatever reason the `username` key does not exist, then it will use
    # the last value in the cache as a fallback.
    account_cache: list[dict[str, Any]]

    # The most recent account login. This is the username/principal name,
    # for example: `user@domain.com`. This is used to get the most recent
    # user if multiple users exist in the cache.
    recent_username: str